"use client";

import { ChangeEvent, Dispatch, SetStateAction, useState } from "react";

type Item = { id: number; merchant: string; date: string; description: string; cents: number; category: string; requested?: boolean };
type Page = "home" | "spending" | "requests" | "approvals";
const categories = ["Meals", "Travel", "Transport", "Supplies", "Software", "Other"];
const seed: Item[] = [
  { id: 1, merchant: "The Daily Grind", date: "Sep 24", description: "Team coffee meeting", cents: 1845, category: "Meals" },
  { id: 2, merchant: "Metro Transit", date: "Sep 22", description: "Client site travel", cents: 650, category: "Transport" },
  { id: 3, merchant: "Harbor Hotel", date: "Sep 18", description: "Conference stay", cents: 24800, category: "Travel" },
  { id: 4, merchant: "Paper & Pen", date: "Sep 15", description: "Workshop supplies", cents: 4275, category: "Supplies", requested: true },
];
function money(cents: number) { return "$" + (cents / 100).toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 }); }

export function Dashboard() {
  const [page, setPage] = useState<Page>("home");
  const [items, setItems] = useState(seed);
  const [capture, setCapture] = useState(false);
  const [notice, setNotice] = useState("");
  const notify = (text: string) => { setNotice(text); setTimeout(() => setNotice(""), 2800); };
  const nav = (next: Page) => { setPage(next); window.scrollTo(0, 0); };
  return <main className="min-h-screen bg-[#f7f9fc] text-slate-900 lg:flex">
    <aside className="border-b border-slate-200 bg-white p-4 lg:fixed lg:inset-y-0 lg:w-64 lg:border-b-0 lg:border-r">
      <button onClick={() => nav("home")} className="flex items-center gap-3 px-2 text-left"><span className="grid size-10 place-items-center rounded-xl bg-blue-600 text-xl text-white">✦</span><span className="font-bold">reimburst<span className="block text-xs font-medium text-slate-400">expense intelligence</span></span></button>
      <nav className="mt-7 flex gap-1 overflow-x-auto lg:flex-col"><Nav label="Overview" active={page === "home"} onClick={() => nav("home")} /><Nav label="My spending" active={page === "spending"} onClick={() => nav("spending")} /><Nav label="Request drafts" active={page === "requests"} onClick={() => nav("requests")} /><Nav label="Approvals" active={page === "approvals"} onClick={() => nav("approvals")} /></nav>
      
    </aside>
    <section className="min-w-0 flex-1 lg:ml-64"><header className="flex h-16 items-center justify-between border-b border-slate-200 bg-white px-6"><span className="text-sm text-slate-500">September 2026</span><span className="grid size-9 place-items-center rounded-full bg-slate-900 text-xs font-bold text-white">RS</span></header><div className="mx-auto max-w-6xl px-5 py-8 sm:px-9">
      {page === "home" && <Home items={items} capture={() => setCapture(true)} nav={nav} />}
      {page === "spending" && <Spending items={items} capture={() => setCapture(true)} />}
      {page === "requests" && <Requests items={items} setItems={setItems} notify={notify} />}
      {page === "approvals" && <Approvals notify={notify} />}
    </div></section>
    <button onClick={() => setCapture(true)} className="fixed bottom-5 right-5 rounded-full bg-blue-600 px-5 py-3 text-sm font-bold text-white shadow-lg">＋ Scan receipt</button>
    {capture && <Capture close={() => setCapture(false)} add={(item) => { setItems(old => [item, ...old]); setCapture(false); notify("Receipt processed. Review it in My spending."); }} />}
    {notice && <div className="fixed bottom-24 right-5 rounded-xl bg-slate-900 px-4 py-3 text-sm text-white">{notice}</div>}
  </main>;
}

function Nav({ label, active, onClick }: { label: string; active: boolean; onClick: () => void }) { return <button onClick={onClick} className={"shrink-0 rounded-lg px-3 py-2.5 text-left text-sm font-medium " + (active ? "bg-blue-50 text-blue-700" : "text-slate-500 hover:bg-slate-50")}>{label}</button>; }
function Tile({ label, value, note }: { label: string; value: string; note: string }) { return <section className="rounded-xl border border-slate-200 bg-white p-5"><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-2xl font-bold">{value}</p><p className="mt-2 text-xs font-medium text-emerald-600">{note}</p></section>; }
function Home({ items, capture, nav }: { items: Item[]; capture: () => void; nav: (p: Page) => void }) {
  const total = items.reduce((s, i) => s + i.cents, 0); const ready = items.filter(i => !i.requested).reduce((s, i) => s + i.cents, 0);
  return <><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold text-blue-600">YOUR WORKSPACE</p><h1 className="mt-1 text-3xl font-bold">Good afternoon, Richard.</h1><p className="mt-2 text-slate-500">Keep expenses moving, from receipt to reimbursement.</p></div><button onClick={capture} className="rounded-lg bg-blue-600 px-5 py-3 text-sm font-bold text-white">Scan a receipt</button></div><div className="mt-7 grid gap-4 sm:grid-cols-3"><Tile label="Captured this month" value={money(total)} note={String(items.length) + " receipts"} /><Tile label="Ready to request" value={money(ready)} note="Confirmed items" /><Tile label="Reimbursed" value="$1,284.20" note="This year" /></div><div className="mt-7 grid gap-6 lg:grid-cols-[1.4fr_.8fr]"><section className="rounded-xl border border-slate-200 bg-white p-5"><div className="flex justify-between"><div><h2 className="font-bold">Recent activity</h2><p className="mt-1 text-sm text-slate-500">Your latest captured expenses</p></div><button onClick={() => nav("spending")} className="text-sm font-bold text-blue-600">View all →</button></div><div className="mt-4 divide-y divide-slate-100">{items.slice(0, 3).map(i => <div className="flex justify-between py-3" key={i.id}><span><b>{i.merchant}</b><small className="block text-slate-500">{i.description} · {i.date}</small></span><b>{money(i.cents)}</b></div>)}</div></section><section className="rounded-xl bg-slate-900 p-6 text-white"><p className="text-sm font-semibold text-blue-200">NEXT STEP</p><h2 className="mt-3 text-xl font-bold">Turn expenses into a clear request.</h2><p className="mt-3 text-sm leading-6 text-slate-300">Choose confirmed expenses, edit a ready-to-send email draft, or move into the approval workflow.</p><button onClick={() => nav("requests")} className="mt-6 text-sm font-bold underline">Create a request →</button></section></div></>;
}

function Spending({ items, capture }: { items: Item[]; capture: () => void }) {
  const [filter, setFilter] = useState("All"); const visible = filter === "All" ? items : items.filter(i => i.category === filter);
  return <><div className="flex justify-between gap-4"><div><p className="text-sm font-semibold text-blue-600">PERSONAL SPENDING</p><h1 className="mt-1 text-3xl font-bold">Know where it goes.</h1><p className="mt-2 text-slate-500">Confirmed expenses grouped by category.</p></div><button onClick={capture} className="h-fit rounded-lg border border-slate-300 bg-white px-4 py-2 text-sm font-bold">Add receipt</button></div><div className="mt-7 flex flex-wrap gap-2">{["All", ...categories].map(c => <button key={c} onClick={() => setFilter(c)} className={"rounded-full px-3 py-1.5 text-sm " + (filter === c ? "bg-slate-900 text-white" : "bg-white ring-1 ring-slate-200")}>{c}</button>)}</div><section className="mt-6 overflow-hidden rounded-xl border border-slate-200 bg-white"><div className="border-b border-slate-100 p-5"><h2 className="font-bold">Expense history</h2></div><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="p-4">DATE</th><th>MERCHANT & ITEM</th><th>CATEGORY</th><th className="pr-4 text-right">AMOUNT</th></tr></thead><tbody>{visible.map(i => <tr className="border-t border-slate-100" key={i.id}><td className="p-4 text-slate-500">{i.date}</td><td><b>{i.merchant}</b><small className="block text-slate-500">{i.description}</small></td><td><span className="rounded-full bg-blue-50 px-2 py-1 text-xs text-blue-700">{i.category}</span></td><td className="pr-4 text-right font-bold">{money(i.cents)}</td></tr>)}</tbody></table></section></>;
}

function Requests({ items, setItems, notify }: { items: Item[]; setItems: Dispatch<SetStateAction<Item[]>>; notify: (s: string) => void }) {
  const [chosen, setChosen] = useState<number[]>([]); const [payer, setPayer] = useState("Northstar Studio"); const [draft, setDraft] = useState(false); const selected = items.filter(i => chosen.includes(i.id)); const total = selected.reduce((s, i) => s + i.cents, 0); const toggle = (id: number) => setChosen(old => old.includes(id) ? old.filter(x => x !== id) : [...old, id]); const generate = () => { setItems(old => old.map(i => chosen.includes(i.id) ? { ...i, requested: true } : i)); setChosen([]); setDraft(true); notify("Email draft generated. Edit it before sending."); };
  return <><div><p className="text-sm font-semibold text-blue-600">OUTBOUND REQUESTS</p><h1 className="mt-1 text-3xl font-bold">Create a reimbursement request.</h1><p className="mt-2 text-slate-500">Select expenses, then make the email draft your own.</p></div><div className="mt-7 grid gap-6 lg:grid-cols-[1fr_330px]"><section className="overflow-hidden rounded-xl border border-slate-200 bg-white"><div className="border-b border-slate-100 p-5"><h2 className="font-bold">Available expenses</h2></div>{items.map(i => <label className={"flex items-center gap-4 border-b border-slate-100 p-4 " + (i.requested ? "bg-slate-50 opacity-55" : "cursor-pointer")} key={i.id}><input type="checkbox" disabled={i.requested} checked={chosen.includes(i.id)} onChange={() => toggle(i.id)} /><span className="flex-1"><b>{i.merchant}</b><small className="block text-slate-500">{i.description}{i.requested ? " · already requested" : ""}</small></span><b>{money(i.cents)}</b></label>)}</section><aside className="h-fit rounded-xl border border-slate-200 bg-white p-5"><h2 className="font-bold">Request summary</h2><p className="mt-2 text-sm text-slate-500">{selected.length} selected</p><p className="mt-3 text-3xl font-bold">{money(total)}</p><label className="mt-5 block text-sm font-medium">External payer<input className="mt-2 w-full rounded-lg border border-slate-300 p-2" value={payer} onChange={e => setPayer(e.target.value)} /></label><button disabled={!selected.length} onClick={generate} className="mt-5 w-full rounded-lg bg-blue-600 p-3 text-sm font-bold text-white disabled:bg-slate-300">Generate email draft</button></aside></div>{draft && <section className="mt-7 rounded-xl border border-blue-200 bg-white p-5"><h2 className="font-bold">Email draft</h2><p className="mt-1 text-sm text-slate-500">Review and edit it before you send it yourself.</p><input className="mt-5 w-full rounded-lg border border-slate-300 p-2" defaultValue={"Reimbursement request — " + money(total)} /><textarea className="mt-3 min-h-40 w-full rounded-lg border border-slate-300 p-3" defaultValue={"Hello " + payer + ",\n\nPlease find my reimbursement request for " + money(total) + ". Receipts are attached for review.\n\nThank you,\nRichard"} /><div className="mt-4 flex gap-3"><button onClick={() => notify("Email copied to your clipboard.")} className="rounded-lg border border-slate-300 px-4 py-2 text-sm font-bold">Copy email</button><button onClick={() => notify("Marked as sent in your request history.")} className="rounded-lg bg-emerald-600 px-4 py-2 text-sm font-bold text-white">Mark as sent</button></div></section>}</>;
}

function Approvals({ notify }: { notify: (s: string) => void }) {
  const [status, setStatus] = useState("Submitted"); const [note, setNote] = useState(""); return <><div><p className="text-sm font-semibold text-blue-600">ORGANIZATION WORKFLOW</p><h1 className="mt-1 text-3xl font-bold">Approvals queue.</h1><p className="mt-2 text-slate-500">Review requests with a clear record of every decision.</p></div><div className="mt-7 grid gap-6 lg:grid-cols-[.8fr_1.2fr]"><section className="overflow-hidden rounded-xl border border-slate-200 bg-white"><div className="border-b p-5"><h2 className="font-bold">Requests</h2><p className="mt-1 text-sm text-slate-500">2 awaiting a decision</p></div>{[["Maya Chen", "Harbor Hotel", "$248.00"], ["Jon Bell", "Metro Transit", "$6.50"], ["Richard Su", "Paper & Pen", "$42.75"]].map((x, i) => <button className="flex w-full justify-between border-b p-4 text-left hover:bg-slate-50" key={x[0]}><span><b>{x[0]}</b><small className="block text-slate-500">{x[1]}</small></span><b>{x[2]}</b></button>)}</section><section className="rounded-xl border border-slate-200 bg-white p-6"><div className="flex justify-between"><div><p className="text-sm font-bold text-slate-500">REQUEST #204</p><h2 className="mt-1 text-xl font-bold">Harbor Hotel</h2><p className="mt-1 text-slate-500">Submitted by Maya Chen</p></div><b className="text-xl">$248.00</b></div><div className="mt-6 rounded-lg bg-slate-50 p-4 text-sm">Business expense submitted for review. The receipt was extracted, categorized, and confirmed by the employee.</div><div className="mt-5 border-l border-slate-200 pl-4 text-sm"><b>Receipt confirmed</b><span className="block pb-3 text-slate-500">Sep 24 · Maya Chen</span><b>Request submitted</b><span className="block text-slate-500">Sep 24 · Awaiting approver</span>{status !== "Submitted" && <><b className="mt-3 block text-emerald-700">{status}</b><span className="text-slate-500">Just now · Richard Su</span></>}</div>{status === "Submitted" ? <div className="mt-6 border-t pt-5"><label className="text-sm font-medium">Decision note (optional)<textarea className="mt-2 min-h-20 w-full rounded-lg border border-slate-300 p-2" value={note} onChange={e => setNote(e.target.value)} /></label><button onClick={() => { setStatus("Approved"); notify("Request approved. Maya has been notified."); }} className="mt-3 rounded-lg bg-emerald-600 px-4 py-2 text-sm font-bold text-white">Approve request</button><button onClick={() => notify("Rejection note saved in demo.")} className="ml-3 rounded-lg border border-red-200 px-4 py-2 text-sm font-bold text-red-700">Reject</button></div> : <button onClick={() => { setStatus("Paid"); notify("Payment recorded in the demo ledger."); }} className="mt-6 rounded-lg bg-blue-600 px-4 py-2 text-sm font-bold text-white">Record payment</button>}</section></div></>;
}

function Capture({ close, add }: { close: () => void; add: (i: Item) => void }) {
  const [stage, setStage] = useState("upload"); const [description, setDescription] = useState("Client lunch"); const [amount, setAmount] = useState("42.50"); const [category, setCategory] = useState("Meals"); const upload = (e: ChangeEvent<HTMLInputElement>) => { if (e.target.files && e.target.files[0]) { setStage("processing"); setTimeout(() => setStage("review"), 850); } }; const save = () => add({ id: Date.now(), merchant: "Market Street Cafe", date: "Sep 28", description, cents: Math.round(Number(amount) * 100), category });
  return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-4"><section className="w-full max-w-xl rounded-2xl bg-white p-6 shadow-2xl"><div className="flex justify-between"><div><p className="text-sm font-bold text-blue-600">RECEIPT CAPTURE</p><h2 className="mt-1 text-xl font-bold">{stage === "review" ? "Review extracted details" : "Add a receipt"}</h2></div><button onClick={close} className="text-2xl text-slate-500">×</button></div>{stage === "upload" && <label className="mt-6 flex cursor-pointer flex-col items-center rounded-xl border-2 border-dashed border-blue-200 bg-blue-50 p-12 text-center"><b>Take a photo or choose a file</b><span className="mt-2 text-sm text-slate-500">The demo extracts sample receipt data instantly.</span><input className="sr-only" type="file" accept="image/*" capture="environment" onChange={upload} /></label>}{stage === "processing" && <div className="py-16 text-center"><span className="inline-block size-8 animate-spin rounded-full border-4 border-blue-200 border-t-blue-600" /><p className="mt-5 font-semibold">Extracting receipt details…</p></div>}{stage === "review" && <div className="mt-6"><div className="rounded-lg bg-emerald-50 p-4 text-sm text-emerald-800"><b>Extraction complete.</b> Review any field before confirming.</div><label className="mt-4 block text-sm font-medium">Item description<input className="mt-1 w-full rounded-lg border border-slate-300 p-2" value={description} onChange={e => setDescription(e.target.value)} /></label><div className="mt-3 grid grid-cols-2 gap-3"><label className="text-sm font-medium">Amount (USD)<input className="mt-1 w-full rounded-lg border border-slate-300 p-2" value={amount} onChange={e => setAmount(e.target.value)} /></label><label className="text-sm font-medium">Category<select className="mt-1 w-full rounded-lg border border-slate-300 p-2" value={category} onChange={e => setCategory(e.target.value)}>{categories.map(c => <option key={c}>{c}</option>)}</select></label></div><button onClick={save} className="mt-6 w-full rounded-lg bg-blue-600 p-3 text-sm font-bold text-white">Confirm receipt</button></div>}</section></div>;
}
