/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/receipts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Receipt */
        post: operations["create_receipt_receipts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/receipts/taxonomy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Taxonomy
         * @description The active global taxonomy. Organization scoping is added with P4/P5 auth.
         */
        get: operations["get_taxonomy_receipts_taxonomy_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/receipts/{receipt_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Receipt */
        get: operations["get_receipt_receipts__receipt_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/receipts/{receipt_id}/confirmation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Confirm Receipt
         * @description Persist the reviewed breakdown, requiring an explicit mismatch acknowledgement.
         */
        put: operations["confirm_receipt_receipts__receipt_id__confirmation_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_create_receipt_receipts_post */
        Body_create_receipt_receipts_post: {
            /**
             * Image
             * @description Receipt image to extract
             */
            image: string;
        };
        /** CategoryDetail */
        CategoryDetail: {
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /** ConfirmedLineItem */
        ConfirmedLineItem: {
            /** Id */
            id: number;
            /** Description */
            description: string;
            /** Amount Cents */
            amount_cents: number;
            /** Category */
            category: string;
        };
        /**
         * ExtractionStatus
         * @enum {string}
         */
        ExtractionStatus: "pending" | "processing" | "succeeded" | "failed";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
        };
        /** LineItemDetail */
        LineItemDetail: {
            /** Id */
            id: number;
            /** Description */
            description: string;
            /** Amount Cents */
            amount_cents: number;
            /** Category */
            category: string | null;
            /** Needs Category Review */
            needs_category_review: boolean;
        };
        /** ReceiptConfirmation */
        ReceiptConfirmation: {
            /** Line Items */
            line_items: components["schemas"]["ConfirmedLineItem"][];
            /**
             * Acknowledge Reconciliation Mismatch
             * @default false
             */
            acknowledge_reconciliation_mismatch: boolean;
        };
        /** ReceiptCreated */
        ReceiptCreated: {
            /** Id */
            id: number;
            /** Image Key */
            image_key: string;
            extraction_status: components["schemas"]["ExtractionStatus"];
        };
        /** ReceiptDetail */
        ReceiptDetail: {
            /** Id */
            id: number;
            /** Image Key */
            image_key: string;
            extraction_status: components["schemas"]["ExtractionStatus"];
            /** Merchant */
            merchant: string | null;
            /** Total Cents */
            total_cents: number | null;
            /** Tax Cents */
            tax_cents: number | null;
            /** Currency */
            currency?: string | null;
            /** Extraction Error */
            extraction_error: string | null;
            categorization_status: components["schemas"]["ExtractionStatus"];
            /** Categorization Error */
            categorization_error: string | null;
            /** Line Items */
            line_items: components["schemas"]["LineItemDetail"][];
            reconciliation: components["schemas"]["ReconciliationDetail"];
            /** Confirmed At */
            confirmed_at: string | null;
        };
        /** ReconciliationDetail */
        ReconciliationDetail: {
            /** Line Items Total Cents */
            line_items_total_cents: number;
            /** Receipt Total Cents */
            receipt_total_cents: number | null;
            /** Difference Cents */
            difference_cents: number | null;
            /** Matches */
            matches: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    create_receipt_receipts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_receipt_receipts_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReceiptCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_taxonomy_receipts_taxonomy_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryDetail"][];
                };
            };
        };
    };
    get_receipt_receipts__receipt_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                receipt_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReceiptDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_receipt_receipts__receipt_id__confirmation_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                receipt_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReceiptConfirmation"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReceiptDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
