/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/receipts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Receipt */
        post: operations["create_receipt_receipts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/receipts/taxonomy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Taxonomy
         * @description The active global taxonomy. Organization scoping is added with P4/P5 auth.
         */
        get: operations["get_taxonomy_receipts_taxonomy_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/receipts/{receipt_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Receipt */
        get: operations["get_receipt_receipts__receipt_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/receipts/{receipt_id}/confirmation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Confirm Receipt */
        put: operations["confirm_receipt_receipts__receipt_id__confirmation_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Create an individual account; organization roles are provisioned by an administrator.
         */
        post: operations["register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Notifications */
        get: operations["list_notifications_notifications_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/{notification_id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark Notification Read */
        post: operations["mark_notification_read_notifications__notification_id__read_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organization/receipts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Organization Receipt
         * @description Capture a receipt owned by the development employee for the P4 workflow.
         */
        post: operations["create_organization_receipt_organization_receipts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organization/receipts/{receipt_id}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Organization Receipt Image
         * @description Serve a receipt image to its employee or a same-org authorized reviewer.
         */
        get: operations["organization_receipt_image_organization_receipts__receipt_id__image_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organization/receipts/available": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Available Organization Receipts
         * @description Return confirmed employee receipts that can still be added to a draft.
         */
        get: operations["available_organization_receipts_organization_receipts_available_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organization/receipts/{receipt_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Organization Receipt */
        get: operations["get_organization_receipt_organization_receipts__receipt_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organization/receipts/{receipt_id}/confirmation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Confirm Organization Receipt */
        put: operations["confirm_organization_receipt_organization_receipts__receipt_id__confirmation_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/spending/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Spending History */
        get: operations["get_spending_history_spending_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/spending/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Spending Report */
        get: operations["get_spending_report_spending_report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/spending/export.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Spending Csv */
        get: operations["export_spending_csv_spending_export_csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/outbound-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Outbound Requests */
        get: operations["list_outbound_requests_outbound_requests_get"];
        put?: never;
        /** Create Outbound Request */
        post: operations["create_outbound_request_outbound_requests_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/outbound-requests/{request_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Outbound Request */
        get: operations["get_outbound_request_outbound_requests__request_id__get"];
        /** Update Outbound Request */
        put: operations["update_outbound_request_outbound_requests__request_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/outbound-requests/{request_id}/mark-sent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark Outbound Request Sent */
        post: operations["mark_outbound_request_sent_outbound_requests__request_id__mark_sent_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organization/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Organization Request */
        post: operations["create_organization_request_organization_requests_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organization/requests/{request_id}/payout.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Export Csv Payout
         * @description Dispatch an approved request through the manual CSV payroll fallback.
         *
         *     A request owns one deterministic key and one payout row. Repeating this
         *     endpoint returns the same frozen CSV row, rather than creating a second
         *     payable export or repeating the `approved -> paid` transition.
         */
        post: operations["export_csv_payout_organization_requests__request_id__payout_csv_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organization/requests/{request_id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Organization Request */
        post: operations["submit_organization_request_organization_requests__request_id__submit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organization/requests/{request_id}/retry-synopsis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retry Organization Synopsis
         * @description Retry a failed asynchronous synopsis job without changing workflow state.
         */
        post: operations["retry_organization_synopsis_organization_requests__request_id__retry_synopsis_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organization/requests/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pending Organization Requests */
        get: operations["pending_organization_requests_organization_requests_pending_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organization/requests/approved": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Approved Organization Requests
         * @description List admin-visible requests awaiting the manual payroll CSV export.
         */
        get: operations["approved_organization_requests_organization_requests_approved_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organization/requests/{request_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Organization Request */
        post: operations["approve_organization_request_organization_requests__request_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organization/requests/{request_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject Organization Request */
        post: operations["reject_organization_request_organization_requests__request_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organization/requests/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My Organization Requests */
        get: operations["my_organization_requests_organization_requests_mine_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organization/requests/{request_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Organization Request */
        get: operations["get_organization_request_organization_requests__request_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuditEventDetail */
        AuditEventDetail: {
            /** Id */
            id: number;
            /** Actor Id */
            actor_id: number;
            /** Action */
            action: string;
            /** Payload */
            payload: {
                [key: string]: string;
            } | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** AuthenticatedUser */
        AuthenticatedUser: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            role: components["schemas"]["UserRole"];
            /** Org Id */
            org_id: number | null;
        };
        /** Body_create_organization_receipt_organization_receipts_post */
        Body_create_organization_receipt_organization_receipts_post: {
            /**
             * Image
             * @description Receipt image to extract
             */
            image: string;
        };
        /** Body_create_receipt_receipts_post */
        Body_create_receipt_receipts_post: {
            /**
             * Image
             * @description Receipt image to extract
             */
            image: string;
        };
        /** CategoryDetail */
        CategoryDetail: {
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /** ConfirmedLineItem */
        ConfirmedLineItem: {
            /** Id */
            id: number;
            /** Description */
            description: string;
            /** Amount Cents */
            amount_cents: number;
            /** Category */
            category: string;
        };
        /** Credentials */
        Credentials: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * ExtractionStatus
         * @enum {string}
         */
        ExtractionStatus: "pending" | "processing" | "succeeded" | "failed";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
        };
        /** LineItemDetail */
        LineItemDetail: {
            /** Id */
            id: number;
            /** Description */
            description: string;
            /** Amount Cents */
            amount_cents: number;
            /** Category */
            category: string | null;
            /** Needs Category Review */
            needs_category_review: boolean;
        };
        /** NotificationDetail */
        NotificationDetail: {
            /** Id */
            id: number;
            /** Request Id */
            request_id: number | null;
            /** Kind */
            kind: string;
            /** Title */
            title: string;
            /** Body */
            body: string;
            /** Read At */
            read_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** OrganizationLineItemDetail */
        OrganizationLineItemDetail: {
            /** Id */
            id: number;
            /** Description */
            description: string;
            /** Amount Cents */
            amount_cents: number;
            /** Category */
            category: string | null;
        };
        /** OrganizationReceiptDetail */
        OrganizationReceiptDetail: {
            /** Id */
            id: number;
            /** Image Key */
            image_key: string;
            /** Merchant */
            merchant: string | null;
            /** Date */
            date: string | null;
            /** Total Cents */
            total_cents: number | null;
            /** Tax Cents */
            tax_cents: number | null;
            /** Currency */
            currency: string | null;
            /** Line Items */
            line_items: components["schemas"]["OrganizationLineItemDetail"][];
        };
        /** OrganizationRequestCreate */
        OrganizationRequestCreate: {
            /** Receipt Ids */
            receipt_ids: number[];
        };
        /** OrganizationRequestDetail */
        OrganizationRequestDetail: {
            /** Id */
            id: number;
            /** Employee Id */
            employee_id: number;
            status: components["schemas"]["RequestStatus"];
            /** Currency */
            currency: string;
            /** Synopsis */
            synopsis: string | null;
            synopsis_status: components["schemas"]["ExtractionStatus"];
            /** Synopsis Error */
            synopsis_error: string | null;
            /** Receipt Ids */
            receipt_ids: number[];
            /** Receipts */
            receipts: components["schemas"]["OrganizationReceiptDetail"][];
            /** Audit Events */
            audit_events: components["schemas"]["AuditEventDetail"][];
        };
        /** OutboundItemDetail */
        OutboundItemDetail: {
            /** Line Item Id */
            line_item_id: number;
            /** Receipt Id */
            receipt_id: number;
            /** Description */
            description: string;
            /** Amount Cents */
            amount_cents: number;
            /** Currency */
            currency: string | null;
            /** Merchant */
            merchant: string | null;
            /** Receipt Date */
            receipt_date: string | null;
            /** Category */
            category: string | null;
        };
        /** OutboundRequestCreate */
        OutboundRequestCreate: {
            /** External Payer */
            external_payer: string;
            /** Line Item Ids */
            line_item_ids: number[];
        };
        /** OutboundRequestDetail */
        OutboundRequestDetail: {
            /** Id */
            id: number;
            /** External Payer */
            external_payer: string | null;
            /** Synopsis */
            synopsis: string | null;
            /** Subject */
            subject: string | null;
            /** Body */
            body: string | null;
            status: components["schemas"]["OutboundRequestStatus"];
            generation_status: components["schemas"]["ExtractionStatus"];
            /** Generation Error */
            generation_error: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Sent At */
            sent_at: string | null;
            /** Items */
            items: components["schemas"]["OutboundItemDetail"][];
        };
        /**
         * OutboundRequestStatus
         * @enum {string}
         */
        OutboundRequestStatus: "draft" | "generated" | "sent";
        /** OutboundRequestUpdate */
        OutboundRequestUpdate: {
            /** External Payer */
            external_payer?: string | null;
            /** Synopsis */
            synopsis?: string | null;
            /** Subject */
            subject?: string | null;
            /** Body */
            body?: string | null;
        };
        /** ReceiptConfirmation */
        ReceiptConfirmation: {
            /** Line Items */
            line_items: components["schemas"]["ConfirmedLineItem"][];
            /**
             * Acknowledge Reconciliation Mismatch
             * @default false
             */
            acknowledge_reconciliation_mismatch: boolean;
        };
        /** ReceiptCreated */
        ReceiptCreated: {
            /** Id */
            id: number;
            /** Image Key */
            image_key: string;
            extraction_status: components["schemas"]["ExtractionStatus"];
        };
        /** ReceiptDetail */
        ReceiptDetail: {
            /** Id */
            id: number;
            /** Image Key */
            image_key: string;
            extraction_status: components["schemas"]["ExtractionStatus"];
            /** Merchant */
            merchant: string | null;
            /** Total Cents */
            total_cents: number | null;
            /** Tax Cents */
            tax_cents: number | null;
            /** Currency */
            currency?: string | null;
            /** Extraction Error */
            extraction_error: string | null;
            categorization_status: components["schemas"]["ExtractionStatus"];
            /** Categorization Error */
            categorization_error: string | null;
            /** Line Items */
            line_items: components["schemas"]["LineItemDetail"][];
            reconciliation: components["schemas"]["ReconciliationDetail"];
            /** Confirmed At */
            confirmed_at: string | null;
        };
        /** ReconciliationDetail */
        ReconciliationDetail: {
            /** Line Items Total Cents */
            line_items_total_cents: number;
            /** Receipt Total Cents */
            receipt_total_cents: number | null;
            /** Difference Cents */
            difference_cents: number | null;
            /** Matches */
            matches: boolean;
        };
        /**
         * RequestStatus
         * @enum {string}
         */
        RequestStatus: "draft" | "submitted" | "approved" | "rejected" | "paid";
        /** Session */
        Session: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            role: components["schemas"]["UserRole"];
            /** Org Id */
            org_id: number | null;
            /** Access Token */
            access_token: string;
        };
        /** SpendingGroup */
        SpendingGroup: {
            /** Name */
            name: string;
            /** Currency */
            currency: string | null;
            /** Total Cents */
            total_cents: number;
        };
        /** SpendingHistory */
        SpendingHistory: {
            /** Items */
            items: components["schemas"]["SpendingItem"][];
        };
        /** SpendingItem */
        SpendingItem: {
            /** Receipt Id */
            receipt_id: number;
            /** Line Item Id */
            line_item_id: number;
            /** Merchant */
            merchant: string | null;
            /** Receipt Date */
            receipt_date: string | null;
            /** Currency */
            currency: string | null;
            /** Description */
            description: string;
            /** Amount Cents */
            amount_cents: number;
            /** Category */
            category: string | null;
        };
        /** SpendingReport */
        SpendingReport: {
            /**
             * Group By
             * @enum {string}
             */
            group_by: "category" | "merchant" | "date";
            /** Groups */
            groups: components["schemas"]["SpendingGroup"][];
            /** Total Cents */
            total_cents: number;
        };
        /** TransitionNote */
        TransitionNote: {
            /** Note */
            note?: string | null;
        };
        /**
         * UserRole
         * @enum {string}
         */
        UserRole: "individual" | "employee" | "approver" | "admin";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    create_receipt_receipts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_receipt_receipts_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReceiptCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_taxonomy_receipts_taxonomy_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryDetail"][];
                };
            };
        };
    };
    get_receipt_receipts__receipt_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                receipt_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReceiptDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_receipt_receipts__receipt_id__confirmation_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                receipt_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReceiptConfirmation"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReceiptDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticatedUser"];
                };
            };
        };
    };
    list_notifications_notifications_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationDetail"][];
                };
            };
        };
    };
    mark_notification_read_notifications__notification_id__read_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notification_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_organization_receipt_organization_receipts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_organization_receipt_organization_receipts_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReceiptCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    organization_receipt_image_organization_receipts__receipt_id__image_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                receipt_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": unknown;
                    "image/png": unknown;
                    "image/webp": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    available_organization_receipts_organization_receipts_available_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReceiptDetail"][];
                };
            };
        };
    };
    get_organization_receipt_organization_receipts__receipt_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                receipt_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReceiptDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_organization_receipt_organization_receipts__receipt_id__confirmation_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                receipt_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReceiptConfirmation"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReceiptDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_spending_history_spending_history_get: {
        parameters: {
            query?: {
                start_date?: string | null;
                end_date?: string | null;
                category?: string | null;
                merchant?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpendingHistory"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_spending_report_spending_report_get: {
        parameters: {
            query?: {
                group_by?: "category" | "merchant" | "date";
                start_date?: string | null;
                end_date?: string | null;
                category?: string | null;
                merchant?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpendingReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_spending_csv_spending_export_csv_get: {
        parameters: {
            query?: {
                start_date?: string | null;
                end_date?: string | null;
                category?: string | null;
                merchant?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_outbound_requests_outbound_requests_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutboundRequestDetail"][];
                };
            };
        };
    };
    create_outbound_request_outbound_requests_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OutboundRequestCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutboundRequestDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_outbound_request_outbound_requests__request_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutboundRequestDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_outbound_request_outbound_requests__request_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OutboundRequestUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutboundRequestDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_outbound_request_sent_outbound_requests__request_id__mark_sent_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutboundRequestDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_organization_request_organization_requests_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrganizationRequestCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationRequestDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_csv_payout_organization_requests__request_id__payout_csv_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_organization_request_organization_requests__request_id__submit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationRequestDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_organization_synopsis_organization_requests__request_id__retry_synopsis_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationRequestDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pending_organization_requests_organization_requests_pending_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationRequestDetail"][];
                };
            };
        };
    };
    approved_organization_requests_organization_requests_approved_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationRequestDetail"][];
                };
            };
        };
    };
    approve_organization_request_organization_requests__request_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransitionNote"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationRequestDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_organization_request_organization_requests__request_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransitionNote"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationRequestDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    my_organization_requests_organization_requests_mine_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationRequestDetail"][];
                };
            };
        };
    };
    get_organization_request_organization_requests__request_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationRequestDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
