/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/receipts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Receipt */
        post: operations["create_receipt_receipts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/receipts/taxonomy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Taxonomy
         * @description The active global taxonomy. Organization scoping is added with P4/P5 auth.
         */
        get: operations["get_taxonomy_receipts_taxonomy_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/receipts/{receipt_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Receipt */
        get: operations["get_receipt_receipts__receipt_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/receipts/{receipt_id}/confirmation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Confirm Receipt
         * @description Persist the reviewed breakdown, requiring an explicit mismatch acknowledgement.
         */
        put: operations["confirm_receipt_receipts__receipt_id__confirmation_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/spending/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Spending History */
        get: operations["get_spending_history_spending_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/spending/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Spending Report */
        get: operations["get_spending_report_spending_report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/spending/export.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Spending Csv */
        get: operations["export_spending_csv_spending_export_csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/outbound-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Outbound Requests */
        get: operations["list_outbound_requests_outbound_requests_get"];
        put?: never;
        /** Create Outbound Request */
        post: operations["create_outbound_request_outbound_requests_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/outbound-requests/{request_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Outbound Request */
        get: operations["get_outbound_request_outbound_requests__request_id__get"];
        /** Update Outbound Request */
        put: operations["update_outbound_request_outbound_requests__request_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/outbound-requests/{request_id}/mark-sent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark Outbound Request Sent */
        post: operations["mark_outbound_request_sent_outbound_requests__request_id__mark_sent_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_create_receipt_receipts_post */
        Body_create_receipt_receipts_post: {
            /**
             * Image
             * @description Receipt image to extract
             */
            image: string;
        };
        /** CategoryDetail */
        CategoryDetail: {
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /** ConfirmedLineItem */
        ConfirmedLineItem: {
            /** Id */
            id: number;
            /** Description */
            description: string;
            /** Amount Cents */
            amount_cents: number;
            /** Category */
            category: string;
        };
        /**
         * ExtractionStatus
         * @enum {string}
         */
        ExtractionStatus: "pending" | "processing" | "succeeded" | "failed";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
        };
        /** LineItemDetail */
        LineItemDetail: {
            /** Id */
            id: number;
            /** Description */
            description: string;
            /** Amount Cents */
            amount_cents: number;
            /** Category */
            category: string | null;
            /** Needs Category Review */
            needs_category_review: boolean;
        };
        /** OutboundItemDetail */
        OutboundItemDetail: {
            /** Line Item Id */
            line_item_id: number;
            /** Receipt Id */
            receipt_id: number;
            /** Description */
            description: string;
            /** Amount Cents */
            amount_cents: number;
            /** Currency */
            currency: string | null;
            /** Merchant */
            merchant: string | null;
            /** Receipt Date */
            receipt_date: string | null;
            /** Category */
            category: string | null;
        };
        /** OutboundRequestCreate */
        OutboundRequestCreate: {
            /** External Payer */
            external_payer: string;
            /** Line Item Ids */
            line_item_ids: number[];
        };
        /** OutboundRequestDetail */
        OutboundRequestDetail: {
            /** Id */
            id: number;
            /** External Payer */
            external_payer: string | null;
            /** Synopsis */
            synopsis: string | null;
            /** Subject */
            subject: string | null;
            /** Body */
            body: string | null;
            status: components["schemas"]["OutboundRequestStatus"];
            generation_status: components["schemas"]["ExtractionStatus"];
            /** Generation Error */
            generation_error: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Sent At */
            sent_at: string | null;
            /** Items */
            items: components["schemas"]["OutboundItemDetail"][];
        };
        /**
         * OutboundRequestStatus
         * @enum {string}
         */
        OutboundRequestStatus: "draft" | "generated" | "sent";
        /** OutboundRequestUpdate */
        OutboundRequestUpdate: {
            /** External Payer */
            external_payer?: string | null;
            /** Synopsis */
            synopsis?: string | null;
            /** Subject */
            subject?: string | null;
            /** Body */
            body?: string | null;
        };
        /** ReceiptConfirmation */
        ReceiptConfirmation: {
            /** Line Items */
            line_items: components["schemas"]["ConfirmedLineItem"][];
            /**
             * Acknowledge Reconciliation Mismatch
             * @default false
             */
            acknowledge_reconciliation_mismatch: boolean;
        };
        /** ReceiptCreated */
        ReceiptCreated: {
            /** Id */
            id: number;
            /** Image Key */
            image_key: string;
            extraction_status: components["schemas"]["ExtractionStatus"];
        };
        /** ReceiptDetail */
        ReceiptDetail: {
            /** Id */
            id: number;
            /** Image Key */
            image_key: string;
            extraction_status: components["schemas"]["ExtractionStatus"];
            /** Merchant */
            merchant: string | null;
            /** Total Cents */
            total_cents: number | null;
            /** Tax Cents */
            tax_cents: number | null;
            /** Currency */
            currency?: string | null;
            /** Extraction Error */
            extraction_error: string | null;
            categorization_status: components["schemas"]["ExtractionStatus"];
            /** Categorization Error */
            categorization_error: string | null;
            /** Line Items */
            line_items: components["schemas"]["LineItemDetail"][];
            reconciliation: components["schemas"]["ReconciliationDetail"];
            /** Confirmed At */
            confirmed_at: string | null;
        };
        /** ReconciliationDetail */
        ReconciliationDetail: {
            /** Line Items Total Cents */
            line_items_total_cents: number;
            /** Receipt Total Cents */
            receipt_total_cents: number | null;
            /** Difference Cents */
            difference_cents: number | null;
            /** Matches */
            matches: boolean;
        };
        /** SpendingGroup */
        SpendingGroup: {
            /** Name */
            name: string;
            /** Currency */
            currency: string | null;
            /** Total Cents */
            total_cents: number;
        };
        /** SpendingHistory */
        SpendingHistory: {
            /** Items */
            items: components["schemas"]["SpendingItem"][];
        };
        /** SpendingItem */
        SpendingItem: {
            /** Receipt Id */
            receipt_id: number;
            /** Line Item Id */
            line_item_id: number;
            /** Merchant */
            merchant: string | null;
            /** Receipt Date */
            receipt_date: string | null;
            /** Currency */
            currency: string | null;
            /** Description */
            description: string;
            /** Amount Cents */
            amount_cents: number;
            /** Category */
            category: string | null;
        };
        /** SpendingReport */
        SpendingReport: {
            /**
             * Group By
             * @enum {string}
             */
            group_by: "category" | "merchant" | "date";
            /** Groups */
            groups: components["schemas"]["SpendingGroup"][];
            /** Total Cents */
            total_cents: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    create_receipt_receipts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_receipt_receipts_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReceiptCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_taxonomy_receipts_taxonomy_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryDetail"][];
                };
            };
        };
    };
    get_receipt_receipts__receipt_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                receipt_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReceiptDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_receipt_receipts__receipt_id__confirmation_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                receipt_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReceiptConfirmation"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReceiptDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_spending_history_spending_history_get: {
        parameters: {
            query?: {
                start_date?: string | null;
                end_date?: string | null;
                category?: string | null;
                merchant?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpendingHistory"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_spending_report_spending_report_get: {
        parameters: {
            query?: {
                group_by?: "category" | "merchant" | "date";
                start_date?: string | null;
                end_date?: string | null;
                category?: string | null;
                merchant?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpendingReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_spending_csv_spending_export_csv_get: {
        parameters: {
            query?: {
                start_date?: string | null;
                end_date?: string | null;
                category?: string | null;
                merchant?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_outbound_requests_outbound_requests_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutboundRequestDetail"][];
                };
            };
        };
    };
    create_outbound_request_outbound_requests_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OutboundRequestCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutboundRequestDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_outbound_request_outbound_requests__request_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutboundRequestDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_outbound_request_outbound_requests__request_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OutboundRequestUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutboundRequestDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_outbound_request_sent_outbound_requests__request_id__mark_sent_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutboundRequestDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
